<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260209214811 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE `order` (OR_ID VARCHAR(16) NOT NULL, OR_REFERENCE_UNIQUE VARCHAR(32) NOT NULL, OR_STATUS VARCHAR(255) DEFAULT \'D\' NOT NULL, OR_SENT_TO_KITCHEN_AT DATETIME DEFAULT NULL, OR_READY_AT DATETIME DEFAULT NULL, OR_SERVED_AT DATETIME DEFAULT NULL, OR_CANCELLED_AT DATETIME DEFAULT NULL, OR_CANCELLATION_REASON LONGTEXT DEFAULT NULL, OR_TOTAL_AMOUNT NUMERIC(17, 2) NOT NULL, OR_CREATED_AT DATETIME NOT NULL, OR_UPDATED_AT DATETIME DEFAULT NULL, OR_PLATFORM_TABLE VARCHAR(16) NOT NULL, OR_TABLET VARCHAR(16) NOT NULL, UNIQUE INDEX UNIQ_F529939833E7914A (OR_REFERENCE_UNIQUE), INDEX IDX_F52993983E89803A (OR_PLATFORM_TABLE), INDEX IDX_F52993987EA5443A (OR_TABLET), PRIMARY KEY (OR_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE `order_item` (OI_ID VARCHAR(16) NOT NULL, OI_QUANTITY INT NOT NULL, OI_UNIT_PRICE_ORDER NUMERIC(17, 2) NOT NULL, OI_ITEM_STATUS VARCHAR(1) NOT NULL, OI_COOKING_AT DATETIME DEFAULT NULL, OI_READY_AT DATETIME DEFAULT NULL, OI_CREATED_AT DATETIME NOT NULL, OI_UPDATED_AT DATETIME DEFAULT NULL, OI_ORDER VARCHAR(16) NOT NULL, OI_PRODUCT VARCHAR(16) NOT NULL, INDEX IDX_52EA1F097D8B2395 (OI_ORDER), INDEX IDX_52EA1F0936F45A4 (OI_PRODUCT), PRIMARY KEY (OI_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE `order_item_option` (OO_ID VARCHAR(16) NOT NULL, OO_PRICE_SNAPSHOT NUMERIC(17, 2) NOT NULL, OO_CREATED_AT DATETIME NOT NULL, OO_UPDATED_AT DATETIME DEFAULT NULL, OO_ORDER_ITEM VARCHAR(16) NOT NULL, OO_OPTION_ITEM VARCHAR(16) NOT NULL, INDEX IDX_C7CD0AF94706463B (OO_ORDER_ITEM), INDEX IDX_C7CD0AF9C2D438DE (OO_OPTION_ITEM), PRIMARY KEY (OO_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993983E89803A FOREIGN KEY (OR_PLATFORM_TABLE) REFERENCES `platform_table` (PT_ID)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993987EA5443A FOREIGN KEY (OR_TABLET) REFERENCES `tablet` (TB_ID)');
        $this->addSql('ALTER TABLE `order_item` ADD CONSTRAINT FK_52EA1F097D8B2395 FOREIGN KEY (OI_ORDER) REFERENCES `order` (OR_ID)');
        $this->addSql('ALTER TABLE `order_item` ADD CONSTRAINT FK_52EA1F0936F45A4 FOREIGN KEY (OI_PRODUCT) REFERENCES `product` (PD_ID)');
        $this->addSql('ALTER TABLE `order_item_option` ADD CONSTRAINT FK_C7CD0AF94706463B FOREIGN KEY (OO_ORDER_ITEM) REFERENCES `order_item` (OI_ID)');
        $this->addSql('ALTER TABLE `order_item_option` ADD CONSTRAINT FK_C7CD0AF9C2D438DE FOREIGN KEY (OO_OPTION_ITEM) REFERENCES `option_item` (OI_ID)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993983E89803A');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993987EA5443A');
        $this->addSql('ALTER TABLE `order_item` DROP FOREIGN KEY FK_52EA1F097D8B2395');
        $this->addSql('ALTER TABLE `order_item` DROP FOREIGN KEY FK_52EA1F0936F45A4');
        $this->addSql('ALTER TABLE `order_item_option` DROP FOREIGN KEY FK_C7CD0AF94706463B');
        $this->addSql('ALTER TABLE `order_item_option` DROP FOREIGN KEY FK_C7CD0AF9C2D438DE');
        $this->addSql('DROP TABLE `order`');
        $this->addSql('DROP TABLE `order_item`');
        $this->addSql('DROP TABLE `order_item_option`');
    }
}
