<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206234335 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE `activity` (AC_ID INT AUTO_INCREMENT NOT NULL, AC_ACTIVITY VARCHAR(20) NOT NULL, AC_ACTIVITY_DESCRIPTION VARCHAR(100) DEFAULT NULL, AC_RESSOURCE_NAME VARCHAR(50) NOT NULL, AC_RESSOURCE_IDENTIFIER VARCHAR(16) DEFAULT NULL, AC_USER VARCHAR(16) NOT NULL, AC_DATE DATETIME NOT NULL, AC_TRIGGERED_BY VARCHAR(16) DEFAULT NULL, INDEX IDX_AC74095A375259F1 (AC_TRIGGERED_BY), PRIMARY KEY (AC_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE `profile` (PR_ID VARCHAR(16) NOT NULL, PR_LABEL VARCHAR(120) NOT NULL, PR_PERSON_TYPE VARCHAR(15) NOT NULL, PR_PERMISSION LONGTEXT NOT NULL, PR_ACTIVE TINYINT NOT NULL, PR_CREATED_AT DATETIME NOT NULL, PR_UPDATED_AT DATETIME DEFAULT NULL, PRIMARY KEY (PR_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE `user` (US_ID VARCHAR(16) NOT NULL, US_EMAIL VARCHAR(180) DEFAULT NULL, US_ROLES JSON NOT NULL, US_PASSWORD VARCHAR(255) NOT NULL, US_PHONE VARCHAR(15) DEFAULT NULL, US_DISPLAY_NAME VARCHAR(120) DEFAULT NULL, US_DELETED TINYINT DEFAULT 0 NOT NULL, US_LOCKED TINYINT DEFAULT 0 NOT NULL, US_IS_CONFIRMED TINYINT DEFAULT 0 NOT NULL, US_MUST_CHANGE_PASSWORD TINYINT DEFAULT 0 NOT NULL, US_PERSON_TYPE VARCHAR(15) NOT NULL, US_HOLDER_ID VARCHAR(16) DEFAULT NULL, US_HOLDER_TYPE VARCHAR(255) DEFAULT NULL, US_SIDE_ROLES LONGTEXT DEFAULT NULL, US_CREATED_AT DATETIME NOT NULL, US_UPDATED_AT DATETIME DEFAULT NULL, US_PROFILE VARCHAR(16) DEFAULT NULL, INDEX IDX_8D93D649581032C8 (US_PROFILE), UNIQUE INDEX UNIQ_USER_EMAIL (US_EMAIL), UNIQUE INDEX UNIQ_USER_PHONE (US_PHONE), UNIQUE INDEX UNIQ_HOLDER (US_HOLDER_ID), PRIMARY KEY (US_ID)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE `activity` ADD CONSTRAINT FK_AC74095A375259F1 FOREIGN KEY (AC_TRIGGERED_BY) REFERENCES `user` (US_ID)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D649581032C8 FOREIGN KEY (US_PROFILE) REFERENCES `profile` (PR_ID)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE `activity` DROP FOREIGN KEY FK_AC74095A375259F1');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D649581032C8');
        $this->addSql('DROP TABLE `activity`');
        $this->addSql('DROP TABLE `profile`');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
